### ISSUE TITLE
Bug: Screenshot Feature doesn't work

### ISSUE THREAD

**Issue by Spidersouris** [lynchjames/obsidian-mind-map#9]
Hello there,

When trying the screenshot feature in the latest version, it doesn't work. Nothing gets pasted in my clipboard, and the follow error happens in the console:

```
copy-image.ts:33 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at drawInlineSVG (eval at <anonymous> (app://obsidian.md/app.js:1:685677), <anonymous>:32205:17)
    at generateImage (eval at <anonymous> (app://obsidian.md/app.js:1:685677), <anonymous>:32199:12)
    at copyImageToClipboard (eval at <anonymous> (app://obsidian.md/app.js:1:685677), <anonymous>:32183:15)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:685677), <anonymous>:32254:47)
    at HTMLDivElement.<anonymous> (app://obsidian.md/app.js:1:476743)
```

**Comment by lynchjames** [comment]
Would you be able to share the contents of the note you are using to generate the mind map? There may be characters in the mind map text items that could cause this error.

**Comment by lynchjames** [comment]
This should be fixed in [1.0.3](https://github.com/lynchjames/obsidian-mind-map/releases/tag/1.0.3).

**Comment by Spidersouris** [comment]
Unfortunately, the issue persists. After running a few tests, I found that it is indeed a issue related to non-Latin characters. When the mind map contains special characters such as é, è, French quotation marks («  »), etc., the same error that I've posted on GitHub will trigger. Otherwise, it works fine.
